server:
  # Run this service on a new port
  port: 8086

spring:
  application:
    name: booking-service

  # --- 1. Order DB (MySQL) Connection ---
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: Slow_bo@t2004
    driver-class-name: com.mysql.cj.jdbc.Driver

  # --- 2. Real-Time Data Store (Redis) Connection ---
  data:
    redis:
      host: localhost
      port: 6379

  # --- JPA/Hibernate Configuration ---
  jpa:
    hibernate:
      # 'none' because we created the table in Workbench
      ddl-auto: none
    open-in-view: false
    show-sql: true

# --- Custom Configuration ---
# This is the URL for the inventory-service API we already built
# We make it a property so it's easy to change later
inventory:
  service:
    url: "http://localhost:8085/api/inventory/events"

waitingroom:
  service:
    url: "http://localhost:8087/api/waitingroom"

    jwt:
      secret: 7K9mP2nQ5tU8wB1dF4gH6jI0kM3nO7pR9sT2uV5xY8zA1cE4fG7hJ0kL3mN6oP9r
      expiration: 86400000