services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=devroot
    ports: ["3306:3306"]

  flyway:
    image: flyway/flyway:10
    command: -configFiles=/flyway/conf/flyway.conf migrate
    volumes:
      - ./db-migrations/sql:/flyway/sql
      - ./db-migrations/conf:/flyway/conf
    depends_on: [mysql]
